#!/bin/bash

ADD=0

while getopts a OPT ; do
    case $OPT in
        a) ADD=1;;
	*) usage; exit 1;;
    esac
done

TOPDIR=""
while true; do
    if [ -d .git ] ; then
        TOPDIR=${PWD}
        break
    fi
    if [ $(realpath .) = "/" ] ; then
        echo "git didn't found" >&2
        exit 1
    fi
    cd ../
done

cd $TOPDIR

# We should also regard shared objects as executables to handle Position-Independent Executable (PIE). 
# `file` reports this kind of executables as shared objects.
BINS=$(find . -type f -exec file {} \; | grep -E ': ELF .*(executable|shared object),' | awk -F: '{print $1}')
for b in $BINS ; do
    BASE=$(basename $b)
    DIR=$(dirname $b)
    GITIGNORE=$DIR/.gitignore
    if [ ! -e $GITIGNORE ] ; then
        touch $GITIGNORE
    fi
    if grep -qv "^${BASE}$" $GITIGNORE ; then
        echo $BASE >> $GITIGNORE
    fi
    if [ $ADD -eq 1 ] ; then
        git add $GITIGNORE
    fi
done
